In [3]:
# Random Forest Example from Geeksforgeeks.com

In [4]:
# https://www.geeksforgeeks.org/random-forest-regression-in-python/

In [5]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
data = pd.read_csv('Position_Salaries.csv')
print(data)

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000


In [12]:
data.shape

(10, 3)

In [21]:
data.dtypes

Position    object
Level        int64
Salary       int64
dtype: object

In [18]:
data.info

<bound method DataFrame.info of             Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000>

In [13]:
data.columns

Index(['Position', 'Level', 'Salary'], dtype='object')

In [14]:
data.describe()

Level          Salary
count  10.00000       10.000000
mean    5.50000   249500.000000
std     3.02765   299373.883668
min     1.00000    45000.000000
25%     3.25000    65000.000000
50%     5.50000   130000.000000
75%     7.75000   275000.000000
max    10.00000  1000000.000000

In [23]:
# convert column "Col" to category dtype
data["Position"] = data["Position"].astype("category")

In [26]:
data.dtypes

Position    category
Level          int64
Salary         int64
dtype: object

In [27]:
print(data['Position'].unique())

['Business Analyst', 'Junior Consultant', 'Senior Consultant', 'Manager', 'Country Manager', 'Region Manager', 'Partner', 'Senior Partner', 'C-level', 'CEO']
Categories (10, object): ['Business Analyst', 'C-level', 'CEO', 'Country Manager', ..., 'Partner', 'Region Manager', 'Senior Consultant', 'Senior Partner']


In [28]:
data['Position'].value_counts()

Business Analyst     1
C-level              1
CEO                  1
Country Manager      1
Junior Consultant    1
Manager              1
Partner              1
Region Manager       1
Senior Consultant    1
Senior Partner       1
Name: Position, dtype: int64

In [29]:
one_hot_encoded_data = pd.get_dummies(data, columns = ['Position'])
print(one_hot_encoded_data)

   Level   Salary  Position_Business Analyst  Position_C-level  Position_CEO  \
0      1    45000                          1                 0             0   
1      2    50000                          0                 0             0   
2      3    60000                          0                 0             0   
3      4    80000                          0                 0             0   
4      5   110000                          0                 0             0   
5      6   150000                          0                 0             0   
6      7   200000                          0                 0             0   
7      8   300000                          0                 0             0   
8      9   500000                          0                 1             0   
9     10  1000000                          0                 0             1   

   Position_Country Manager  Position_Junior Consultant  Position_Manager  \
0                         0               

In [31]:
one_hot_encoded_data.dtypes

Level                         int64
Salary                        int64
Position_Business Analyst     uint8
Position_C-level              uint8
Position_CEO                  uint8
Position_Country Manager      uint8
Position_Junior Consultant    uint8
Position_Manager              uint8
Position_Partner              uint8
Position_Region Manager       uint8
Position_Senior Consultant    uint8
Position_Senior Partner       uint8
dtype: object

In [35]:
df1=one_hot_encoded_data.iloc[:,[0,2,3,4,5,6,7,8,9,10,11,1]]

In [36]:
df1.dtypes

Level                         int64
Position_Business Analyst     uint8
Position_C-level              uint8
Position_CEO                  uint8
Position_Country Manager      uint8
Position_Junior Consultant    uint8
Position_Manager              uint8
Position_Partner              uint8
Position_Region Manager       uint8
Position_Senior Consultant    uint8
Position_Senior Partner       uint8
Salary                        int64
dtype: object

In [32]:
one_hot_encoded_data.shape

(10, 12)

In [37]:
x = df1.iloc[:, : -1]
y = df1.iloc[:, -1:]

In [42]:
x.columns

Index(['Level', 'Position_Business Analyst', 'Position_C-level',
       'Position_CEO', 'Position_Country Manager',
       'Position_Junior Consultant', 'Position_Manager', 'Position_Partner',
       'Position_Region Manager', 'Position_Senior Consultant',
       'Position_Senior Partner'],
      dtype='object')

In [41]:
y.columns

Index(['Salary'], dtype='object')

In [38]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor
 
# create regressor object
regressor = RandomForestRegressor(n_estimators=100,
                                  random_state=0)
 
# fit the regressor with x and y data
regressor.fit(x, y)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(random_state=0)

In [40]:
import numpy as geek
 
# array = geek.arrange(8)
# The 'numpy' module has no attribute 'arrange'
array1 = geek.arange(8)
print("Original array : \n", array1)
 
# shape array with 2 rows and 4 columns
array2 = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n",
      array2)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]


In [39]:
# test the output by changing values
Y_pred = regressor.predict(np.array([6.5]).reshape(1, 1))

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


ValueError: X has 1 features, but RandomForestRegressor is expecting 11 features as input.

In [ ]:
# Visualising the Random Forest Regression results
 
# arrange for creating a range of values
# from min value of x to max
# value of x with a difference of 0.01
# between two consecutive values
X_grid = np.arange(min(x), max(x), 0.01)
 
# reshape for reshaping the data
# into a len(X_grid)*1 array,
# i.e. to make a column out of the X_grid value
X_grid = X_grid.reshape((len(X_grid), 1))
 
# Scatter plot for original data
plt.scatter(x, y, color='blue')
 
# plot predicted data
plt.plot(X_grid, regressor.predict(X_grid),
         color='green')
plt.title('Random Forest Regression')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

In [45]:
# https://www.geeksforgeeks.org/how-to-develop-a-random-forest-ensemble-in-python/

In [46]:
# Import scikit-learn dataset library
from sklearn import datasets
 
# Load dataset
iris = datasets.load_iris()

In [48]:
#  print the label species(setosa ,
# versicolor , virginica )
print(iris.target_names)
 
# print the names of the four features
print(iris.feature_names)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [50]:
# To convert Iris sklearn dataset to pandas Dataframe use:

In [51]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['target'] = pd.Series(iris.target)

In [52]:
# print the iris data(top 5 records)
print(iris.data[0:5])
 
# print the iris labels ( 0:setosa ,
# 1:versicolor , 2:viriginica)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [53]:
#  Creating a Dataframe of given iris dataset.
import pandas as pd
data = pd.DataFrame({
    'sepal length': iris.data[:, 0],
    'sepal width': iris.data[:, 1],
    'petal length': iris.data[:, 2],
    'petal width': iris.data[:, 3],
    'species': iris.target
})
 
data.head()

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [54]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
 
X = data[['sepal length', 'sepal width',
          'petal length', 'petal width']]  # Features
y = data['species']  # Labels
 
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3)  # 70% training and 30% test

In [56]:
# Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier
 
# Create a Gaussian Classifier
clf = RandomForestClassifier()
 
# Train the model using the training sets
# y_pred = clf.predict(X_test)
clf.fit(X_train, y_train)
 
y_pred = clf.predict(X_test)

In [58]:
# Import scikit-learn metrics
# module for accuracy calculation
from sklearn import metrics
 
# Number of right values predicted right
# and wrong values predicted wrong
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)
 
# Model Accuracy how often is the
# classifier correct ?
print("Accuracy : ", metrics.accuracy_score(y_test, y_pred))

[[13  0  0]
 [ 0 14  1]
 [ 0  2 15]]
Accuracy :  0.9333333333333333
